local model = require("map_tag_generator.planner")
local gui = require("map_tag_generator.gui.planner")
local sources = require("map_tag_generator.sources")
local player, surface, team, other_force, a, b, c
-- Chart requests finish on the engine tick after setup, before each test starts.
ticks_between_tests(1)
local function session() return storage.recipe_planner.sessions[player.index] end
local function emit(id, data)
    data.name, data.tick, data.player_index = id, game.tick, player.index
    script.get_event_handler(id)(data)
end
local function click(element)
    emit(defines.events.on_gui_click, {element = element, button = defines.mouse_button_type.left})
end
local function choose(name)
    click(session().gui.recipe)
    local prototype = prototypes.recipe[name]
    local product = prototype.main_product or prototype.products[1]
    local search = session().gui.search
    search.text = product.name
    emit(defines.events.on_gui_text_changed, {element = search})
    local slot = session().gui["product_"..product.type.."/"..product.name]
    assert(slot and slot.visible, "Product missing from filtered picker: "..product.name)
    click(slot)
    if session().picker then click(session().gui["recipe_"..name]) end
    assert(session().draft.recipe == name)
end
local function select(mode, entities)
    local modes = {replace = defines.events.on_player_selected_area, add = defines.events.on_player_alt_selected_area,
        remove = defines.events.on_player_alt_reverse_selected_area}
    emit(modes[mode], {item = "map_tag_generator_planner_tool", entities = entities, surface = surface,
        area = {left_top = {x = -3, y = -3}, right_bottom = {x = 25, y = 4}}})
end
local function near(position, x, y)
    assert(position and math.abs(position.x - x) < 0.0001 and math.abs(position.y - y) < 0.0001, "wrong planner position")
end
local function draft()
    local value = model.new(player)
    assert(model.set_recipe(value, "electronic-circuit"))
    return value
end
local function populated()
    local value = draft()
    assert(model.select(value, "item/iron-plate", {a, b}, "add", surface.index))
    assert(model.select(value, "item/copper-cable", {c}, "add", surface.index))
    return value
end
local function apply(value)
    local result, err = model.apply(player, value)
    assert(result, err and err[1])
    return result, storage.recipe_planner.plans[result.id].tag
end
local function start()
    emit(defines.events.on_lua_shortcut, {prototype_name = "map_tag_generator_open_planner"})
    click(session().gui.new)
    choose("electronic-circuit")
end
local function cleanup()
    local p = game.get_player(1)
    gui.close(p)
    sources.clear(p.index)
    local preferences = model.preferences(p)
    preferences.researched_only, preferences.show_retired, preferences.highlight_sources = true, false, false
    preferences.picker_group = nil
    p.clear_cursor()
    p.force = game.forces.player
    for _, plan in pairs(storage.recipe_planner.plans) do
        if plan.tag and plan.tag.valid then plan.tag.destroy() end
    end
    storage.recipe_planner.plans = {}
    if surface then
        for _, entity in pairs(surface.find_entities()) do entity.destroy() end
    end
end

before_all(function()
    surface = game.create_surface("recipe-planner-tests", {width = 128, height = 128})
    surface.request_to_generate_chunks({0, 0}, 2)
    surface.force_generate_chunk_requests()
    local tiles = {}
    for x = -32, 32 do for y = -32, 32 do tiles[#tiles + 1] = {name = "lab-dark-1", position = {x, y}} end end
    surface.set_tiles(tiles)
    team, other_force = game.create_force("planner-tests-team"), game.create_force("planner-tests-other")
    team.chart(surface, {{-32, -32}, {32, 32}})
end)
before_each(function()
    cleanup()
    player = game.get_player(1)
    player.set_controller({type = defines.controllers.god})
    player.force = team
    team.recipes["electronic-circuit"].enabled = true
    team.recipes["iron-gear-wheel"].enabled = true
    player.teleport({0, 8}, surface)
    team.chart(surface, {{-32, -32}, {32, 32}})
    a = surface.create_entity({name = "wooden-chest", position = {0.5, 0.5}, force = team})
    b = surface.create_entity({name = "transport-belt", position = {10.5, 0.5}, force = team})
    c = surface.create_entity({name = "wooden-chest", position = {20.5, 0.5}, force = team})
end)
after_each(cleanup)

describe("source navigation", function()
    test("Find replaces and expires only its own navigation pin", function()
        local personal = player.add_pin({entity = c})
        sources.find(player, a)
        local first = storage.recipe_planner.highlights[player.index].guide.pin
        assert(first.targets[1] == a and first.always_visible)
        sources.find(player, b)
        local second = storage.recipe_planner.highlights[player.index].guide.pin
        assert(not first.valid and second.targets[1] == b and personal.valid)
        sources.expire({tick = game.tick + 1799})
        assert(second.valid)
        sources.expire({tick = game.tick + 1800})
        assert(not second.valid and personal.valid)
        personal.destroy()
    end)
    test("removed targets and dismissed pins leave no stale guidance", function()
        sources.find(player, a)
        local pin = storage.recipe_planner.highlights[player.index].guide.pin
        a.destroy()
        sources.expire({tick = game.tick})
        assert(not pin.valid and not storage.recipe_planner.highlights[player.index].guide)
        sources.find(player, b)
        storage.recipe_planner.highlights[player.index].guide.pin.destroy()
        sources.expire({tick = game.tick})
        assert(not storage.recipe_planner.highlights[player.index].guide)
        sources.find(player, c)
        local final = storage.recipe_planner.highlights[player.index].guide.pin
        sources.clear(player.index)
        assert(not final.valid)
    end)
end)

describe("recipe planner selection", function()
    test("choosing a recipe prepares ingredients without creating a plan", function()
        start()
        assert(session().draft.recipe == "electronic-circuit")
        assert(#session().draft.ingredients == 2)
        assert(#model.list(player) == 0)
        assert(not session().gui.apply.enabled)
    end)
    test("copy from machine uses its configured recipe", function()
        start()
        local machine = surface.create_entity({name = "assembling-machine-1", position = {4.5, 4.5}, force = team})
        machine.set_recipe("iron-gear-wheel")
        click(session().gui.machine)
        select("replace", {machine})
        assert(session().draft.recipe == "iron-gear-wheel")
        assert(not session().selecting)
    end)
    test("ambiguous machine selection does not replace the chosen recipe", function()
        start()
        local first = surface.create_entity({name = "assembling-machine-1", position = {4.5, 4.5}, force = team})
        local second = surface.create_entity({name = "assembling-machine-1", position = {8.5, 4.5}, force = team})
        first.set_recipe("iron-gear-wheel"); second.set_recipe("iron-gear-wheel")
        click(session().gui.machine)
        select("replace", {first, second})
        assert(session().draft.recipe == "electronic-circuit")
    end)
    test("ingredient selection accepts empty chests and belts and retains the window position", function()
        start()
        session().gui.frame.location = {x = 70, y = 90}
        local key = session().draft.ingredients[1].key
        click(session().gui.select_1)
        select("replace", {a})
        select("add", {a, b})
        assert(table_size(model.ingredient(session().draft, key).anchors) == 2)
        select("remove", {a})
        near(model.center(session().draft), 10.5, 0.5)
        assert(session().gui.frame.location.x == 70 and session().gui.frame.location.y == 90)
        assert(player.cursor_stack.name == "map_tag_generator_planner_tool")
    end)
    test("each assigned ingredient has equal weight regardless of its anchor count", function()
        local position, assigned, total = model.center(populated())
        near(position, 13, 0.5)
        assert(assigned == 2 and total == 2)
    end)
    test("partial plans exclude unassigned ingredients and visibly label the marker", function()
        local value = draft()
        model.select(value, "item/iron-plate", {a, b}, "replace", surface.index)
        local _, tag = apply(value)
        near(tag.position, 5.5, 0.5)
        assert(tag.text:find("[1/2]", 1, true))
    end)
    test("zero anchors cannot save a plan or create a marker", function()
        assert(not model.apply(player, draft()))
        assert(#model.list(player) == 0)
        assert(#team.find_chart_tags(surface) == 0)
    end)
    test("foreign tools and cross-surface selections do not change ingredient sources", function()
        start(); click(session().gui.select_1)
        emit(defines.events.on_player_selected_area, {item = "unrelated-selection-tool", entities = {},
            surface = surface, area = {left_top = {x = 0, y = 0}, right_bottom = {x = 1, y = 1}}})
        local value = populated()
        assert(not model.select(value, "item/iron-plate", {c}, "replace", game.surfaces.nauvis.index))
        near(model.center(value), 13, 0.5)
        assert(model.center(session().draft) == nil)
    end)
    test("recipe changes retain only matching ingredient assignments", function()
        local value = populated()
        model.set_recipe(value, "iron-gear-wheel")
        assert(#value.ingredients == 1 and value.ingredients[1].name == "iron-plate")
        near(model.center(value), 5.5, 0.5)
    end)
end)

describe("planner interface", function()
    test("the close button dismisses an editor directly without saving its draft", function()
        start()
        click(session().gui.select_1); select("replace", {a})
        local frame = session().gui.frame
        click(session().gui.close)
        assert(not session() and not frame.valid)
        assert(not player.cursor_stack.valid_for_read and #model.list(player) == 0)
    end)
    test("Cancel closes the editor rather than forcing navigation through the list", function()
        start()
        click(session().gui.cancel)
        assert(not session() and #model.list(player) == 0)
    end)
    test("the close button dismisses the recipe picker and underlying draft together", function()
        start(); click(session().gui.recipe)
        local frame, modal = session().gui.frame, session().gui.picker_frame
        click(session().gui.picker_close)
        assert(not session() and not frame.valid and not modal.valid and #model.list(player) == 0)
    end)
    test("the normal GUI close event dismisses the editor", function()
        start()
        assert(player.opened == session().gui.frame)
        player.opened = nil
        after_ticks(1, function() assert(not session()) end)
    end)
    test("the picker keeps its draft and workspace through modal navigation and normal close", function()
        start()
        local draft, frame = session().draft, session().gui.frame
        click(session().gui.recipe)
        after_ticks(1, function()
            assert(session().draft == draft and frame.valid and not frame.enabled)
            assert(player.opened == session().gui.picker_frame)
            click(session().gui.back_to_plan)
            assert(session().draft == draft and frame.enabled and player.opened == frame)
            click(session().gui.recipe)
            player.opened = nil
            after_ticks(1, function() assert(not session() and not frame.valid) end)
        end)
    end)
    test("unapplied changes distinguish source edits, reverted names, and committed plans", function()
        local saved = apply(populated())
        gui.open(player); click(session().gui["plan_"..saved.id])
        assert(not session().gui.draft_status.visible)
        local title = session().gui.title
        title.text = "Temporary title"
        emit(defines.events.on_gui_text_changed, {element = title})
        assert(session().gui.draft_status.visible)
        title.text = saved.title
        emit(defines.events.on_gui_text_changed, {element = title})
        assert(not session().gui.draft_status.visible)
        click(session().gui.clear_1)
        assert(session().gui.draft_status.visible)
        click(session().gui.select_1); select("add", {a, b})
        assert(not session().gui.draft_status.visible)
        select("remove", {b})
        assert(session().gui.draft_status.visible)
        click(session().gui.apply)
        assert(not session().gui.draft_status.visible)
        near(model.center(model.load(player, saved.id)), 10.5, 0.5)
        click(session().gui.new)
        assert(session().gui.draft_status.visible)
    end)
    test("detaching the modal editor for world selection does not close the planner", function()
        start(); click(session().gui.select_1)
        after_ticks(1, function()
            assert(session() and session().selecting and player.opened ~= session().gui.frame)
            select("replace", {a})
            near(model.center(session().draft), 0.5, 0.5)
        end)
    end)
    test("the planner shortcut toggles an open editor closed", function()
        start()
        emit(defines.events.on_lua_shortcut, {prototype_name = "map_tag_generator_open_planner"})
        assert(not session() and #model.list(player) == 0)
    end)
    test("a surface without a custom display name is not reported as missing", function()
        local saved = apply(populated())
        surface.localised_name = nil
        gui.open(player); click(session().gui["plan_"..saved.id])
        assert(session().gui.surface.caption == surface.name)
    end)
    test("surface navigation isolates plans and discards private edits without relocating sources", function()
        local saved = apply(populated())
        local remote_surface = game.create_surface("planner-navigation-surface", {width = 64, height = 64})
        remote_surface.request_to_generate_chunks({0, 0}, 1)
        remote_surface.force_generate_chunk_requests()
        remote_surface.set_tiles({{name = "lab-dark-1", position = {0, 0}}})
        team.chart(remote_surface, {{-32, -32}, {32, 32}})
        after_ticks(1, function()
            player.teleport({0, 8}, remote_surface)
            local anchor = remote_surface.create_entity({name = "wooden-chest", position = {0.5, 0.5}, force = team})
            local remote_draft = draft()
            model.select(remote_draft, "item/iron-plate", {anchor}, "add", remote_surface.index)
            local remote_plan = apply(remote_draft)
            player.teleport({0, 8}, surface)
            sources.toggle(player)
            gui.open(player)
            assert(session().gui["plan_"..saved.id] and not session().gui["plan_"..remote_plan.id])
            click(session().gui["plan_"..saved.id])
            click(session().gui.clear_1)
            assert(#storage.recipe_planner.highlights[player.index].plans == 4)
            local function browse(index)
                local selector = session().gui.surface_selector
                for choice, value in ipairs(session().surface_choices) do
                    if value == index then selector.selected_index = choice end
                end
                emit(defines.events.on_gui_selection_state_changed, {element = selector})
            end
            browse(remote_surface.index)
            assert(not session().draft and not session().gui["plan_"..saved.id])
            assert(session().gui["plan_"..remote_plan.id] and not session().gui.new.enabled)
            assert(#storage.recipe_planner.highlights[player.index].plans == 8)
            click(session().gui.new)
            assert(not session().draft and session().gui.notice_panel.visible)
            click(session().gui["plan_"..remote_plan.id])
            assert(session().draft.surface_index == remote_surface.index)
            click(session().gui.select_1)
            assert(not session().selecting and session().gui.notice_panel.visible)
            browse(surface.index)
            assert(session().gui.new.enabled)
            click(session().gui.new)
            assert(session().draft.surface_index == surface.index)
            near(model.center(model.load(player, saved.id)), 13, 0.5)
            gui.close(player)
            game.delete_surface(remote_surface)
        end)
    end)
    test("the recipe filter distinguishes current research from prototype defaults", function()
        team.technologies.automation.researched = false
        team.recipes["assembling-machine-1"].enabled = false
        start(); click(session().gui.recipe)
        local search = session().gui.search
        search.text = "assembling-machine-1"
        emit(defines.events.on_gui_text_changed, {element = search})
        assert(not session().gui["product_item/assembling-machine-1"].visible)
        click(session().gui.show_unresearched)
        assert(session().gui["product_item/assembling-machine-1"].visible)
        click(session().gui.show_unresearched)
        team.technologies.automation.researched = true
        team.recipes["assembling-machine-1"].enabled = false
        gui.refresh_picker(player)
        assert(session().gui["product_item/assembling-machine-1"].visible)
        team.technologies.automation.researched = false
    end)
    test("the picker excludes blueprint parameters with no assignable ingredients", function()
        start(); click(session().gui.recipe)
        click(session().gui.show_unresearched)
        local search = session().gui.search
        search.text = "parameter-0"
        emit(defines.events.on_gui_text_changed, {element = search})
        assert(session().gui.recipe_empty.visible)
        search.text = "iron-gear-wheel"
        emit(defines.events.on_gui_text_changed, {element = search})
        assert(session().gui["product_item/iron-gear-wheel"].visible)
    end)
    test("recipe filter preference survives reopening the planner", function()
        start(); click(session().gui.recipe)
        click(session().gui.show_unresearched)
        gui.close(player)
        start(); click(session().gui.recipe)
        assert(session().gui.show_unresearched.toggled)
    end)
    test("products with multiple recipes require an explicit recipe choice", function()
        team.recipes["solid-fuel-from-heavy-oil"].enabled = true
        team.recipes["solid-fuel-from-light-oil"].enabled = true
        start(); click(session().gui.recipe)
        local search = session().gui.search
        search.text = "solid-fuel"
        emit(defines.events.on_gui_text_changed, {element = search})
        click(session().gui["product_item/solid-fuel"])
        assert(session().draft.recipe == "electronic-circuit")
        assert(session().gui["recipe_solid-fuel-from-heavy-oil"].visible)
        assert(session().gui["recipe_solid-fuel-from-light-oil"].visible)
        click(session().gui["recipe_solid-fuel-from-light-oil"])
        assert(session().draft.recipe == "solid-fuel-from-light-oil")
        assert(model.ingredient(session().draft, "fluid/light-oil"))
    end)
    test("product group navigation survives reopening and searches reveal matching groups", function()
        start(); click(session().gui.recipe)
        local production
        for _, group in ipairs(session().picker.groups) do
            if group.name == "production" then production = group end
        end
        click(session().gui[production.button])
        assert(session().gui[production.pane].visible)
        local search = session().gui.search
        search.text = "iron-gear-wheel"
        emit(defines.events.on_gui_text_changed, {element = search})
        assert(not session().gui[production.pane].visible)
        assert(session().picker.group == prototypes.item["iron-gear-wheel"].group.name)
        gui.close(player)
        start(); click(session().gui.recipe)
        assert(session().picker.group == "production")
    end)
    test("retiring and reactivating a plan updates highlights without deleting its marker", function()
        local saved, tag = apply(populated())
        gui.open(player); click(session().gui["plan_"..saved.id])
        emit(defines.events.on_lua_shortcut, {prototype_name = "map_tag_generator_highlight_sources"})
        local highlights = storage.recipe_planner.highlights[player.index].plans
        assert(#highlights == 6 and player.is_shortcut_toggled("map_tag_generator_highlight_sources"))
        click(session().gui.retire)
        for _, object in ipairs(highlights) do assert(not object.valid) end
        assert(#storage.recipe_planner.highlights[player.index].plans == 0)
        assert(tag.valid and #model.list(player) == 0 and #model.list(player, true) == 1)
        click(session().gui.show_retired)
        click(session().gui.retire)
        assert(#storage.recipe_planner.highlights[player.index].plans == 6 and tag.valid)
        near(tag.position, 13, 0.5)
    end)
    test("shared anchors are highlighted once and survive original entity removal", function()
        apply(populated()); apply(populated())
        sources.toggle(player)
        local highlights = storage.recipe_planner.highlights[player.index].plans
        assert(#highlights == 6)
        a.destroy(); b.destroy(); c.destroy()
        for _, object in ipairs(highlights) do
            assert(object.valid and object.players[1].index == player.index)
        end
        sources.toggle(player)
        for _, object in ipairs(highlights) do assert(not object.valid) end
    end)
    test("clearing draft sources updates highlights immediately and Cancel restores saved sources", function()
        local saved = apply(populated())
        sources.toggle(player)
        gui.open(player); click(session().gui["plan_"..saved.id])
        local old = storage.recipe_planner.highlights[player.index].plans
        click(session().gui.clear_1)
        for _, object in ipairs(old) do assert(not object.valid, "removed sources remain highlighted") end
        local highlights = storage.recipe_planner.highlights[player.index].plans
        assert(#highlights == 2)
        for _, object in ipairs(highlights) do near(object.target.position, 20.5, 0.5) end
        assert(model.center(model.load(player, saved.id)))
        gui.close(player)
        assert(#storage.recipe_planner.highlights[player.index].plans == 6)
    end)
    test("right-drag removal updates highlights before Apply and preserves other active plans", function()
        local saved = apply(populated())
        local shared = draft()
        model.select(shared, "item/iron-plate", {a}, "add", surface.index)
        apply(shared)
        sources.toggle(player)
        gui.open(player); click(session().gui["plan_"..saved.id])
        click(session().gui.select_1); select("remove", {a, b})
        local highlights = storage.recipe_planner.highlights[player.index].plans
        assert(#highlights == 4, "only the unshared removed source should disappear")
        for _, object in ipairs(highlights) do assert(object.target.position.x ~= b.position.x) end
        click(session().gui.apply)
        gui.close(player)
        assert(#storage.recipe_planner.highlights[player.index].plans == 4)
    end)
    test("source lookup feedback is dismissible and clears on source edits without losing the draft", function()
        start()
        click(session().gui.select_1); select("replace", {a})
        click(session().gui.find_1)
        assert(session().gui.notice_panel.visible)
        click(session().gui.dismiss_notice)
        assert(not session().gui.notice_panel.visible)
        near(model.center(session().draft), 0.5, 0.5)
        click(session().gui.find_2)
        assert(session().gui.notice_panel.visible)
        click(session().gui.clear_1)
        assert(not session().gui.notice_panel.visible and not model.center(session().draft))
        assert(session().draft.recipe == "electronic-circuit" and #model.list(player) == 0)
    end)
    test("a stale revision cannot retire a newer saved plan", function()
        local saved = apply(populated())
        local stale = model.load(player, saved.id)
        saved.title = "Updated plan"
        apply(saved)
        assert(not model.retire(player, stale, true))
        assert(not storage.recipe_planner.plans[saved.id].retired)
    end)
    test("closest-source lookup rejects a draft from another force", function()
        local value = populated()
        player.force = other_force
        assert(not sources.closest(player, value, "item/iron-plate"))
        player.force = team
    end)
end)

describe("saved recipe plans", function()
    test("Apply saves, list reopens, and Back leaves the saved marker unchanged", function()
        start(); click(session().gui.select_1); select("replace", {a})
        click(session().gui.apply)
        local id = session().draft.id
        local tag = storage.recipe_planner.plans[id].tag
        click(session().gui.select_1); select("add", {b})
        near(tag.position, 0.5, 0.5)
        click(session().gui.back)
        click(session().gui["plan_"..id])
        near(model.center(session().draft), 0.5, 0.5)
        near(tag.position, 0.5, 0.5)
    end)
    test("reapplying updates the existing marker rather than adding another", function()
        local saved, tag = apply(populated())
        local number = tag.tag_number
        model.select(saved, "item/iron-plate", {c}, "replace", surface.index)
        saved = apply(saved)
        assert(storage.recipe_planner.plans[saved.id].tag.tag_number == number)
        near(tag.position, 20.5, 0.5)
        assert(saved.revision == 2 and #team.find_chart_tags(surface) == 1)
    end)
    test("destroying original sources does not change saved or reopened anchor positions", function()
        local saved, tag = apply(populated())
        a.destroy(); b.destroy(); c.destroy()
        near(tag.position, 13, 0.5)
        near(model.center(model.load(player, saved.id)), 13, 0.5)
    end)
    test("stale drafts cannot overwrite or delete a teammate's revision", function()
        local saved = apply(populated())
        local first, stale = model.load(player, saved.id), model.load(player, saved.id)
        first.title = "Updated by teammate"
        apply(first)
        assert(not model.apply(player, stale))
        assert(not model.delete(player, stale))
        assert(storage.recipe_planner.plans[saved.id].title == "Updated by teammate")
    end)
    test("another force cannot list, load, modify, or delete the plan", function()
        local saved = apply(populated())
        player.force = other_force
        assert(#model.list(player) == 0)
        assert(not model.load(player, saved.id))
        assert(not model.apply(player, saved))
        assert(not model.delete(player, saved))
        player.force = team
        assert(#model.list(player) == 1)
    end)
    test("externally deleted markers are recreated only on Apply", function()
        local saved, tag = apply(populated())
        tag.destroy()
        local reopened = model.load(player, saved.id)
        assert(#team.find_chart_tags(surface) == 0)
        local _, replacement = apply(reopened)
        near(replacement.position, 13, 0.5)
        assert(#team.find_chart_tags(surface) == 1)
    end)
    test("Apply restores an externally moved marker without leaving an orphan", function()
        local saved, tag = apply(populated())
        local number = tag.tag_number
        tag.surface = game.surfaces.nauvis
        apply(saved)
        assert(tag.surface == surface and tag.tag_number == number)
        assert(#team.find_chart_tags(surface) == 1)
    end)
    test("force merging transfers plan ownership without duplicating its marker", function()
        local source = game.create_force("planner-tests-merged")
        player.force = source
        local saved = apply(populated())
        game.merge_forces(source, team)
        after_ticks(1, function()
            player.force = team
            local reopened = model.load(player, saved.id)
            assert(reopened and reopened.revision == saved.revision + 1)
            apply(reopened)
            assert(#team.find_chart_tags(surface) == 1)
        end)
    end)
    test("plan deletion requires GUI confirmation and preserves unrelated markers", function()
        local saved, tag = apply(populated())
        local manual = team.add_chart_tag(surface, {position = {3, 3}, text = "Unrelated"})
        gui.open(player); click(session().gui["plan_"..saved.id]); click(session().gui.delete)
        assert(tag.valid)
        click(session().gui.delete)
        assert(not tag.valid and manual.valid)
        assert(#model.list(player) == 0)
        manual.destroy()
    end)
    test("clearing the cursor pauses selection without losing a draft", function()
        start(); click(session().gui.select_1); select("replace", {a})
        player.clear_cursor()
        after_ticks(1, function()
            assert(not session().selecting)
            near(model.center(session().draft), 0.5, 0.5)
        end)
    end)
    test("surface changes close an unsaved editor without creating a plan", function()
        start(); click(session().gui.select_1); select("replace", {a})
        player.teleport({0, 0}, game.surfaces.nauvis)
        after_ticks(1, function()
            assert(not session())
            assert(#model.list(player) == 0)
        end)
    end)
    test("missing recipes fail cleanly while leaving a saved plan deletable", function()
        local saved = apply(populated())
        storage.recipe_planner.plans[saved.id].recipe = "removed-recipe"
        storage.recipe_planner.plans[saved.id].ingredients[1].name = "removed-ingredient"
        local reopened = model.load(player, saved.id)
        assert(not model.apply(player, reopened))
        gui.open(player); click(session().gui["plan_"..saved.id])
        assert(not session().gui.apply.enabled)
        assert(model.delete(player, reopened))
    end)
    test("missing surfaces fail cleanly while leaving a saved plan deletable", function()
        local saved = apply(populated())
        local temporary = game.create_surface("planner-deleted-surface")
        storage.recipe_planner.plans[saved.id].surface_index = temporary.index
        game.delete_surface(temporary)
        after_ticks(1, function()
            local reopened = model.load(player, saved.id)
            assert(not model.apply(player, reopened))
            assert(model.delete(player, reopened))
        end)
    end)
    test("saved plans and pending edits survive script reload", function()
        local saved = apply(populated())
        gui.open(player); click(session().gui["plan_"..saved.id])
        gui.activate(player, false, "item/iron-plate")
        select("replace", {a})
    end).after_reload_script(function()
        player = game.get_player(1)
        surface, team = game.surfaces["recipe-planner-tests"], game.forces["planner-tests-team"]
        local current = session()
        local saved = storage.recipe_planner.plans[current.draft.id]
        assert(current.gui.frame.valid and saved.revision == 1)
        near(model.center(current.draft), 10.5, 0.5)
        near(saved.tag.position, 13, 0.5)
        click(current.gui.apply)
        near(saved.tag.position, 10.5, 0.5)
    end)
end)
